# Generated by Django 2.2.19 on 2021-03-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210126_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Количество товара'),
        ),
    ]
