# Generated by Django 2.2.17 on 2021-02-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20210129_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
