# Generated by Django 2.2.17 on 2021-03-03 09:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20210202_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128, verbose_name='Код активации пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 9, 40, 0, 205110, tzinfo=utc), verbose_name='Время жизни ключа'),
        ),
    ]
