# Generated by Django 2.2.19 on 2021-03-06 16:28

from django.db import migrations, transaction


def forward_func(apps, schema_editor):
    try:
        User = apps.get_model("userapp", "User")
        UserProfile = apps.get_model("userapp", "UserProfile")

        with transaction.atomic():
            users = User.objects.all()
            for u in users:
                UserProfile.objects.create(user=u)
    except Exception as exp:
        print(f"Cann't create user profile: {exp}")


def reverse_func(apps, schema_editor):
    try:
        UserProfile = apps.get_model("userapp", "UserProfile")

        with transaction.atomic():
            UserProfile.objects.all().delete()
    except Exception as exp:
        print(f"Cann't delete users profiles: {exp}")


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_user_profile'),
    ]

    operations = [migrations.RunPython(forward_func, reverse_func)]
