# Generated by Django 2.2.19 on 2021-03-09 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_create_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 13, 50, 5, 139292, tzinfo=utc), verbose_name='Время жизни ключа'),
        ),
    ]
