# Generated by Django 2.2.19 on 2021-03-28 16:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_auto_20210322_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 16, 10, 38, 373785, tzinfo=utc), verbose_name='Время жизни ключа'),
        ),
    ]
